# Generated by Django 2.2.7 on 2020-06-25 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('time', models.TimeField(default=datetime.datetime(2020, 6, 25, 10, 30, 52, 614733))),
                ('adharno', models.IntegerField(null=True)),
                ('pancardno', models.IntegerField(null=True)),
                ('licenseno', models.IntegerField(null=True)),
                ('image', models.FileField(upload_to='img/image')),
                ('adharcard', models.FileField(null=True, upload_to='img/adhar')),
                ('pancard', models.FileField(null=True, upload_to='img/pan')),
                ('license', models.FileField(null=True, upload_to='img/license')),
                ('containment', models.CharField(max_length=3)),
                ('symptoms', models.CharField(max_length=3)),
                ('history', models.CharField(max_length=3)),
                ('family', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('host_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('host_phone', models.IntegerField(max_length=10)),
                ('host_image', models.ImageField(upload_to='img/managers')),
                ('host_desc', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('available', models.CharField(default='', max_length=50)),
                ('current_meeting_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('visitor_phone', models.IntegerField(max_length=10)),
                ('visitor_permissions', models.CharField(max_length=100, null=True)),
                ('host', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2020, 6, 25, 10, 30, 52, 614260))),
                ('time_in', models.TimeField(default=datetime.datetime(2020, 6, 25, 10, 30, 52, 614282))),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
