# Generated by Django 2.2.7 on 2020-06-25 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200625_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='adharcard',
            field=models.ImageField(upload_to='img/adhar'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.ImageField(upload_to='img/image'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='license',
            field=models.ImageField(upload_to='img/license'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='pancard',
            field=models.ImageField(upload_to='img/pan'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 14, 57, 53, 852805)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 25, 14, 57, 53, 852079)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 14, 57, 53, 852104)),
        ),
    ]
