# Generated by Django 2.2.7 on 2020-06-25 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200625_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='adharcard',
            field=models.FileField(upload_to='img/adhar'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='image',
            field=models.FileField(upload_to='img/image'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='license',
            field=models.FileField(upload_to='img/license'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='pancard',
            field=models.FileField(upload_to='img/pan'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 17, 45, 56, 75255)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 25, 17, 45, 56, 74654)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2020, 6, 25, 17, 45, 56, 74679)),
        ),
    ]
