# Generated by Django 2.2.7 on 2020-06-26 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200625_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 26, 16, 21, 10, 287698)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 6, 26, 16, 21, 10, 287170)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2020, 6, 26, 16, 21, 10, 287198)),
        ),
    ]
