# Generated by Django 3.0.7 on 2020-07-01 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200630_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='otp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 7, 2, 13, 58, 1, 778977)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 2, 13, 58, 1, 778977)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2020, 7, 2, 13, 58, 1, 778977)),
        ),
    ]
